services:
  jupyterhub:
    image: custom-jupyterhub
    container_name: jupyterhub
    build:
      context: ./custom_jupyterhub_image
    volumes:
      - ./jupyterhub:/srv/jupyterhub
      - /var/run/docker.sock:/var/run/docker.sock
      
      ### Https setup
      #- /etc/letsencrypt/fullchain.pem:/etc/letsencrypt/fullchain.pem
      #- /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem
      
      ### If you want to pass server users to jupyterhub
      #- /etc/passwd:/etc/passwd:ro  
    ports:
      - "8000:8000"
      
      ### HTTPS
      #- "443:8000" 
    environment:
      ### This is a directory in your container; do not change unless you change in jupyterhub_config.py as well.
      - JUPYTERHUB_CONFIG=/srv/jupyterhub/jupyterhub_config.py 
      
      ### Change this path to where the container user_dirs should be saved.
      - BASE_USER_DIR=/neurodesk/users
    restart: unless-stopped
    networks:
      - jupyterhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hub/health"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    ### If db needs upgrade
    #command: >
    #  sh -c "jupyterhub upgrade-db && jupyterhub -f /srv/jupyterhub/jupyterhub_config.py"

  # fail2ban:
  #   container_name: fail2ban_jupyterhub
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   environment:
  #     - TZ=Europe/Vienna
  #     - F2B_DB_PURGE_AGE=14d
  #     - F2B_LOG_TARGET=/data/logs/fail2ban.log
  #     - SLACK_WEBHOOK_URL
  #   image: crazymax/fail2ban:latest
  #   network_mode: host
  #   restart: unless-stopped
  #   volumes:
  #     - ./fail2ban:/data
  #     - ./jupyterhub/logs:/var/log:ro
  #   depends_on:
  #     jupyterhub:
  #       condition: service_healthy

  # slack-notifier:
  #   build:
  #     context: ./slack_notify_docker
  #   container_name: slack_notifier_jupyterhub
  #   volumes:
  #     - ./jupyterhub/jupyterhub.sqlite:/data/jupyterhub.sqlite:ro
  #   environment:
  #     - DATABASE_FILE=/data/jupyterhub.sqlite
  #     - SLACK_WEBHOOK_URL
  #   restart: unless-stopped
  #   depends_on:
  #     jupyterhub:
  #       condition: service_healthy

networks:
  jupyterhub-network:
    external: true
